### ISSUE TITLE
Ch2 BlogController rewrite not accounting for context

### ISSUE THREAD

**Issue by rhythnic** [MostlyAdequate/mostly-adequate-guide#425] opened 2018-03-27 11:43 UTC
First off, excellent book.  I purchased a published book on FP in JS and this one beats it hands down.

The rewrite of the `BlogController` example in chapter 2 isn't equivalent to the first example because without binding the functions, the methods will run with a different context.  An equivalent refactor of the first BlogController example would be

```
const BlogController = {
  index: Views.index.bind(Views),
  show: Views.show.bind(Views),
  create: Db.create.bind(Db),
  update: Db.update.bind(Db),
  destroy: Db.destroy.bind(Db),
};
```

**Comment by KtorZ** [comment] 2018-03-27 11:59
Hey! Thanks for the support and happy that you've enjoyed / you're enjoying the book. 
This issue is known and therefore, a duplicate of #133. 
I haven't got time to update this until now, PRs are welcome :)

**Closed by KtorZ** 2018-03-27 11:59 UTC
