### ISSUE TITLE
When will Part 3 be published?

### ISSUE THREAD

**Issue by adispring** [MostlyAdequate/mostly-adequate-guide#313] opened 2016-10-22 01:46 UTC
Hi, @DrBoolean, when will part 3 of the book be published?
I and my team have already finished reading this book, and introduce Ramda into our Project. FP and the book are great. mostly-adequate-guide is the most elegant book about FP in JavaScript I have ever read. 
We have read your plan about Part 3 of the book, it contains some advance FP concepts we want to learn.
Expect your reply :)

**Comment by kgish** [comment] 2016-10-22 03:54
+1

**Comment by graforlock** [comment] 2016-10-22 10:53
+1

**Comment by aitoroses** [comment] 2016-11-12 16:41
+1

**Comment by kgish** [comment] 2016-11-12 17:37
+1

**Comment by ahstro** [comment] 2017-01-23 12:19
This is a duplicate of #245 :)

**Closed** 2017-10-31 07:59 UTC
